In [1]:
#Import relevant libaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
#Loading and checking dataset
data = pd.read_csv('sampleset.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
#datset statistical data 
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [4]:
#Declaring the dependent and independent variable
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [5]:
#import scaler
from sklearn.preprocessing import StandardScaler

In [6]:
#Declaring object for standard scaler and fitting
scaler = StandardScaler()


In [7]:
scaler.fit(x)

StandardScaler()

In [8]:
scaler.get_params()

{'copy': True, 'with_mean': True, 'with_std': True}

In [9]:
#Transforming unscaled inputs using scaler object
x_scaled = scaler.transform(x)

In [10]:
#outputting transformed data
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [11]:
#Regressions with Scaled features
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [12]:
reg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

In [13]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [14]:
reg.intercept_

3.330238095238095

In [15]:
#creating summary table with new data
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns=["Features"])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [16]:
reg_summary


Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [21]:
#creating new data to predict
new_data = pd.DataFrame(data=[[1500,2],[1801,3],[1402,1],[1901,2],[1604,2]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1500           2
1  1801           3
2  1402           1
3  1901           2
4  1604           2

In [22]:
reg.predict(new_data)

array([261.03701708, 312.74596873, 244.20628566, 329.93438807,
       278.90566192])

In [23]:
#transforming data back to orignal magnitude 
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-3.32292498, -0.07002087],
       [-0.4260924 ,  1.10632974],
       [-4.26607978, -1.24637147],
       [ 0.53631045, -0.07002087],
       [-2.32202602, -0.07002087]])

In [25]:
reg.predict(new_data_scaled)

array([2.75980567, 3.24925193, 2.6060284 , 3.42287593, 2.93177402])